import { AgentCard } from './types';
export const agentRegistry: Record<string, AgentCard> = {
  'code-meridian': { id:'code-meridian', name:'Code Meridian', discipline:'code', weight:0.22, price:48, seniority:'7+ years Staff Engineer', model:{ primary:'groq:llama-3.3-70b-versatile', fallback:['openrouter:qwen/qwen3-coder:free','github:Meta-Llama-3-1-405B-Instruct'] }, description:'Lead for code tasks', systemPromptPath:'./prompts/code-meridian.md' },
  'security-assay': { id:'security-assay', name:'Security Assay', discipline:'security', weight:0.18, price:42, seniority:'8+ years AppSec payments', model:{ primary:'openrouter:poolside/laguna-s-2.1:free', fallback:['groq:llama-3.3-70b-versatile'] }, description:'Always on for pay tasks', systemPromptPath:'./prompts/security-assay.md' },
  'data-silt': { id:'data-silt', name:'Data Silt', discipline:'data', weight:0.14, price:36, seniority:'6+ years Data Engineer Neon', model:{ primary:'openrouter:thinkingmachines/inkling-small:free', fallback:['groq:llama-3.3-70b-versatile'] }, description:'DB migrations agent_runs', systemPromptPath:'./prompts/data-silt.md' },
  'ops-conduit': { id:'ops-conduit', name:'Ops Conduit', discipline:'ops', weight:0.12, price:32, seniority:'6+ years SRE Vercel', model:{ primary:'groq:llama-3.3-70b-versatile', fallback:['openrouter:google/gemini-3-flash-preview:free'] }, description:'Vercel cleanup DATABASE_URL', systemPromptPath:'./prompts/ops-conduit.md' },
  'research-gyre': { id:'research-gyre', name:'Research Gyre', discipline:'research', weight:0.12, price:28, seniority:'5+ years Research eval', model:{ primary:'openrouter:meta-llama/llama-3.3-70b-instruct:free', fallback:['groq:llama-3.3-70b-versatile'] }, description:'Audit fix explanation', systemPromptPath:'./prompts/research-gyre.md' },
  'support-sable': { id:'support-sable', name:'Support Sable', discipline:'support', weight:0.12, price:26, seniority:'5+ years DX receipts', model:{ primary:'groq:llama-3.3-70b-versatile', fallback:['openrouter:qwen/qwen3-30b-a3b:free'] }, description:'User errors Groq login loop', systemPromptPath:'./prompts/support-sable.md' },
  'creative-vellum': { id:'creative-vellum', name:'Creative Vellum', discipline:'creative', weight:0.10, price:24, seniority:'5+ years Product Designer', model:{ primary:'openrouter:google/gemini-3-flash-preview:free', fallback:['groq:llama-3.3-70b-versatile'] }, description:'Landing OG PWA', systemPromptPath:'./prompts/creative-vellum.md' }
};
const sum = Object.values(agentRegistry).reduce((s,a)=>s+a.weight,0);
if (Math.abs(sum-1.0)>0.001) throw new Error(`Weights sum ${sum}`);
