/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssayRouteImport } from './routes/assay'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as HeraldRouteImport } from './routes/herald'
import { Route as InstallRouteImport } from './routes/install'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LookoutRouteImport } from './routes/lookout'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TrawlRouteImport } from './routes/trawl'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WardenRouteImport } from './routes/warden'
import { Route as AgentsSlugRouteImport } from './routes/agents.$slug'
import { Route as ApiAgentsRouteImport } from './routes/api/agents'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiTasksRouteImport } from './routes/api/tasks'
import { Route as BtcIdRouteImport } from './routes/btc_.$id'
import { Route as HeraldCodeRouteImport } from './routes/herald.$code'
import { Route as LibrarySlugRouteImport } from './routes/library_.$slug'
import { Route as StudioNewRouteImport } from './routes/studio_.new'
import { Route as ApiAgentsAgentIdRouteImport } from './routes/api/agents.$agentId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCoinbaseWebhookRouteImport } from './routes/api/coinbase/webhook'
import { Route as ApiScoutTickRouteImport } from './routes/api/scout/tick'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiTasksTaskIdRouteImport } from './routes/api/tasks.$taskId'
import { Route as ApiWeightsSlugRouteImport } from './routes/api/weights.$slug'
import { Route as StudioTuneSlugRouteImport } from './routes/studio_.tune.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssayRoute = AssayRouteImport.update({
  id: '/assay',
  path: '/assay',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HeraldRoute = HeraldRouteImport.update({
  id: '/herald',
  path: '/herald',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LookoutRoute = LookoutRouteImport.update({
  id: '/lookout',
  path: '/lookout',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TrawlRoute = TrawlRouteImport.update({
  id: '/trawl',
  path: '/trawl',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WardenRoute = WardenRouteImport.update({
  id: '/warden',
  path: '/warden',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugRoute = AgentsSlugRouteImport.update({
  id: '/agents/$slug',
  path: '/agents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRoute = ApiAgentsRouteImport.update({
  id: '/api/agents',
  path: '/api/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const BtcIdRoute = BtcIdRouteImport.update({
  id: '/btc_/$id',
  path: '/btc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HeraldCodeRoute = HeraldCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => HeraldRoute,
} as any)
const LibrarySlugRoute = LibrarySlugRouteImport.update({
  id: '/library_/$slug',
  path: '/library/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioNewRoute = StudioNewRouteImport.update({
  id: '/studio_/new',
  path: '/studio/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsAgentIdRoute = ApiAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => ApiAgentsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoinbaseWebhookRoute = ApiCoinbaseWebhookRouteImport.update({
  id: '/api/coinbase/webhook',
  path: '/api/coinbase/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScoutTickRoute = ApiScoutTickRouteImport.update({
  id: '/api/scout/tick',
  path: '/api/scout/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksTaskIdRoute = ApiTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => ApiTasksRoute,
} as any)
const ApiWeightsSlugRoute = ApiWeightsSlugRouteImport.update({
  id: '/api/weights/$slug',
  path: '/api/weights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioTuneSlugRoute = StudioTuneSlugRouteImport.update({
  id: '/studio_/tune/$slug',
  path: '/studio/tune/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assay': typeof AssayRoute
  '/developers': typeof DevelopersRoute
  '/herald': typeof HeraldRouteWithChildren
  '/install': typeof InstallRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/lookout': typeof LookoutRoute
  '/studio': typeof StudioRoute
  '/support': typeof SupportRoute
  '/trawl': typeof TrawlRoute
  '/wallet': typeof WalletRoute
  '/warden': typeof WardenRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/btc/$id': typeof BtcIdRoute
  '/herald/$code': typeof HeraldCodeRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/studio/new': typeof StudioNewRoute
  '/api/agents/$agentId': typeof ApiAgentsAgentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/coinbase/webhook': typeof ApiCoinbaseWebhookRoute
  '/api/scout/tick': typeof ApiScoutTickRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
  '/api/weights/$slug': typeof ApiWeightsSlugRoute
  '/studio/tune/$slug': typeof StudioTuneSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assay': typeof AssayRoute
  '/developers': typeof DevelopersRoute
  '/herald': typeof HeraldRouteWithChildren
  '/install': typeof InstallRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/lookout': typeof LookoutRoute
  '/studio': typeof StudioRoute
  '/support': typeof SupportRoute
  '/trawl': typeof TrawlRoute
  '/wallet': typeof WalletRoute
  '/warden': typeof WardenRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/btc/$id': typeof BtcIdRoute
  '/herald/$code': typeof HeraldCodeRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/studio/new': typeof StudioNewRoute
  '/api/agents/$agentId': typeof ApiAgentsAgentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/coinbase/webhook': typeof ApiCoinbaseWebhookRoute
  '/api/scout/tick': typeof ApiScoutTickRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
  '/api/weights/$slug': typeof ApiWeightsSlugRoute
  '/studio/tune/$slug': typeof StudioTuneSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assay': typeof AssayRoute
  '/developers': typeof DevelopersRoute
  '/herald': typeof HeraldRouteWithChildren
  '/install': typeof InstallRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/lookout': typeof LookoutRoute
  '/studio': typeof StudioRoute
  '/support': typeof SupportRoute
  '/trawl': typeof TrawlRoute
  '/wallet': typeof WalletRoute
  '/warden': typeof WardenRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/btc_/$id': typeof BtcIdRoute
  '/herald/$code': typeof HeraldCodeRoute
  '/library_/$slug': typeof LibrarySlugRoute
  '/studio_/new': typeof StudioNewRoute
  '/api/agents/$agentId': typeof ApiAgentsAgentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/coinbase/webhook': typeof ApiCoinbaseWebhookRoute
  '/api/scout/tick': typeof ApiScoutTickRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
  '/api/weights/$slug': typeof ApiWeightsSlugRoute
  '/studio_/tune/$slug': typeof StudioTuneSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assay'
    | '/developers'
    | '/herald'
    | '/install'
    | '/library'
    | '/login'
    | '/lookout'
    | '/studio'
    | '/support'
    | '/trawl'
    | '/wallet'
    | '/warden'
    | '/agents/$slug'
    | '/api/agents'
    | '/api/chat'
    | '/api/tasks'
    | '/btc/$id'
    | '/herald/$code'
    | '/library/$slug'
    | '/studio/new'
    | '/api/agents/$agentId'
    | '/api/auth/$'
    | '/api/coinbase/webhook'
    | '/api/scout/tick'
    | '/api/stripe/webhook'
    | '/api/tasks/$taskId'
    | '/api/weights/$slug'
    | '/studio/tune/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assay'
    | '/developers'
    | '/herald'
    | '/install'
    | '/library'
    | '/login'
    | '/lookout'
    | '/studio'
    | '/support'
    | '/trawl'
    | '/wallet'
    | '/warden'
    | '/agents/$slug'
    | '/api/agents'
    | '/api/chat'
    | '/api/tasks'
    | '/btc/$id'
    | '/herald/$code'
    | '/library/$slug'
    | '/studio/new'
    | '/api/agents/$agentId'
    | '/api/auth/$'
    | '/api/coinbase/webhook'
    | '/api/scout/tick'
    | '/api/stripe/webhook'
    | '/api/tasks/$taskId'
    | '/api/weights/$slug'
    | '/studio/tune/$slug'
  id:
    | '__root__'
    | '/'
    | '/assay'
    | '/developers'
    | '/herald'
    | '/install'
    | '/library'
    | '/login'
    | '/lookout'
    | '/studio'
    | '/support'
    | '/trawl'
    | '/wallet'
    | '/warden'
    | '/agents/$slug'
    | '/api/agents'
    | '/api/chat'
    | '/api/tasks'
    | '/btc_/$id'
    | '/herald/$code'
    | '/library_/$slug'
    | '/studio_/new'
    | '/api/agents/$agentId'
    | '/api/auth/$'
    | '/api/coinbase/webhook'
    | '/api/scout/tick'
    | '/api/stripe/webhook'
    | '/api/tasks/$taskId'
    | '/api/weights/$slug'
    | '/studio_/tune/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssayRoute: typeof AssayRoute
  DevelopersRoute: typeof DevelopersRoute
  HeraldRoute: typeof HeraldRouteWithChildren
  InstallRoute: typeof InstallRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  LookoutRoute: typeof LookoutRoute
  StudioRoute: typeof StudioRoute
  SupportRoute: typeof SupportRoute
  TrawlRoute: typeof TrawlRoute
  WalletRoute: typeof WalletRoute
  WardenRoute: typeof WardenRoute
  AgentsSlugRoute: typeof AgentsSlugRoute
  ApiAgentsRoute: typeof ApiAgentsRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiTasksRoute: typeof ApiTasksRouteWithChildren
  BtcIdRoute: typeof BtcIdRoute
  LibrarySlugRoute: typeof LibrarySlugRoute
  StudioNewRoute: typeof StudioNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCoinbaseWebhookRoute: typeof ApiCoinbaseWebhookRoute
  ApiScoutTickRoute: typeof ApiScoutTickRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiWeightsSlugRoute: typeof ApiWeightsSlugRoute
  StudioTuneSlugRoute: typeof StudioTuneSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assay': {
      id: '/assay'
      path: '/assay'
      fullPath: '/assay'
      preLoaderRoute: typeof AssayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herald': {
      id: '/herald'
      path: '/herald'
      fullPath: '/herald'
      preLoaderRoute: typeof HeraldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookout': {
      id: '/lookout'
      path: '/lookout'
      fullPath: '/lookout'
      preLoaderRoute: typeof LookoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trawl': {
      id: '/trawl'
      path: '/trawl'
      fullPath: '/trawl'
      preLoaderRoute: typeof TrawlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warden': {
      id: '/warden'
      path: '/warden'
      fullPath: '/warden'
      preLoaderRoute: typeof WardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug': {
      id: '/agents/$slug'
      path: '/agents/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AgentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents': {
      id: '/api/agents'
      path: '/api/agents'
      fullPath: '/api/agents'
      preLoaderRoute: typeof ApiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/btc_/$id': {
      id: '/btc_/$id'
      path: '/btc/$id'
      fullPath: '/btc/$id'
      preLoaderRoute: typeof BtcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herald/$code': {
      id: '/herald/$code'
      path: '/$code'
      fullPath: '/herald/$code'
      preLoaderRoute: typeof HeraldCodeRouteImport
      parentRoute: typeof HeraldRoute
    }
    '/library_/$slug': {
      id: '/library_/$slug'
      path: '/library/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof LibrarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio_/new': {
      id: '/studio_/new'
      path: '/studio/new'
      fullPath: '/studio/new'
      preLoaderRoute: typeof StudioNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$agentId': {
      id: '/api/agents/$agentId'
      path: '/$agentId'
      fullPath: '/api/agents/$agentId'
      preLoaderRoute: typeof ApiAgentsAgentIdRouteImport
      parentRoute: typeof ApiAgentsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coinbase/webhook': {
      id: '/api/coinbase/webhook'
      path: '/api/coinbase/webhook'
      fullPath: '/api/coinbase/webhook'
      preLoaderRoute: typeof ApiCoinbaseWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scout/tick': {
      id: '/api/scout/tick'
      path: '/api/scout/tick'
      fullPath: '/api/scout/tick'
      preLoaderRoute: typeof ApiScoutTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$taskId': {
      id: '/api/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/api/tasks/$taskId'
      preLoaderRoute: typeof ApiTasksTaskIdRouteImport
      parentRoute: typeof ApiTasksRoute
    }
    '/api/weights/$slug': {
      id: '/api/weights/$slug'
      path: '/api/weights/$slug'
      fullPath: '/api/weights/$slug'
      preLoaderRoute: typeof ApiWeightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio_/tune/$slug': {
      id: '/studio_/tune/$slug'
      path: '/studio/tune/$slug'
      fullPath: '/studio/tune/$slug'
      preLoaderRoute: typeof StudioTuneSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HeraldRouteChildren {
  HeraldCodeRoute: typeof HeraldCodeRoute
}

const HeraldRouteChildren: HeraldRouteChildren = {
  HeraldCodeRoute: HeraldCodeRoute,
}

const HeraldRouteWithChildren =
  HeraldRoute._addFileChildren(HeraldRouteChildren)

interface ApiAgentsRouteChildren {
  ApiAgentsAgentIdRoute: typeof ApiAgentsAgentIdRoute
}

const ApiAgentsRouteChildren: ApiAgentsRouteChildren = {
  ApiAgentsAgentIdRoute: ApiAgentsAgentIdRoute,
}

const ApiAgentsRouteWithChildren = ApiAgentsRoute._addFileChildren(
  ApiAgentsRouteChildren,
)

interface ApiTasksRouteChildren {
  ApiTasksTaskIdRoute: typeof ApiTasksTaskIdRoute
}

const ApiTasksRouteChildren: ApiTasksRouteChildren = {
  ApiTasksTaskIdRoute: ApiTasksTaskIdRoute,
}

const ApiTasksRouteWithChildren = ApiTasksRoute._addFileChildren(
  ApiTasksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssayRoute: AssayRoute,
  DevelopersRoute: DevelopersRoute,
  HeraldRoute: HeraldRouteWithChildren,
  InstallRoute: InstallRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  LookoutRoute: LookoutRoute,
  StudioRoute: StudioRoute,
  SupportRoute: SupportRoute,
  TrawlRoute: TrawlRoute,
  WalletRoute: WalletRoute,
  WardenRoute: WardenRoute,
  AgentsSlugRoute: AgentsSlugRoute,
  ApiAgentsRoute: ApiAgentsRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiTasksRoute: ApiTasksRouteWithChildren,
  BtcIdRoute: BtcIdRoute,
  LibrarySlugRoute: LibrarySlugRoute,
  StudioNewRoute: StudioNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCoinbaseWebhookRoute: ApiCoinbaseWebhookRoute,
  ApiScoutTickRoute: ApiScoutTickRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiWeightsSlugRoute: ApiWeightsSlugRoute,
  StudioTuneSlugRoute: StudioTuneSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
