/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstallRouteImport } from './routes/install'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as AgentsSlugRouteImport } from './routes/agents.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as LibrarySlugRouteImport } from './routes/library_.$slug'
import { Route as StudioNewRouteImport } from './routes/studio_.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugRoute = AgentsSlugRouteImport.update({
  id: '/agents/$slug',
  path: '/agents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySlugRoute = LibrarySlugRouteImport.update({
  id: '/library_/$slug',
  path: '/library/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioNewRoute = StudioNewRouteImport.update({
  id: '/studio_/new',
  path: '/studio/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/api/chat': typeof ApiChatRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/studio/new': typeof StudioNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/api/chat': typeof ApiChatRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/studio/new': typeof StudioNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/api/chat': typeof ApiChatRoute
  '/library_/$slug': typeof LibrarySlugRoute
  '/studio_/new': typeof StudioNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/install'
    | '/library'
    | '/login'
    | '/studio'
    | '/agents/$slug'
    | '/api/chat'
    | '/library/$slug'
    | '/studio/new'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/install'
    | '/library'
    | '/login'
    | '/studio'
    | '/agents/$slug'
    | '/api/chat'
    | '/library/$slug'
    | '/studio/new'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/install'
    | '/library'
    | '/login'
    | '/studio'
    | '/agents/$slug'
    | '/api/chat'
    | '/library_/$slug'
    | '/studio_/new'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstallRoute: typeof InstallRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  StudioRoute: typeof StudioRoute
  AgentsSlugRoute: typeof AgentsSlugRoute
  ApiChatRoute: typeof ApiChatRoute
  LibrarySlugRoute: typeof LibrarySlugRoute
  StudioNewRoute: typeof StudioNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug': {
      id: '/agents/$slug'
      path: '/agents/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AgentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library_/$slug': {
      id: '/library_/$slug'
      path: '/library/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof LibrarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio_/new': {
      id: '/studio_/new'
      path: '/studio/new'
      fullPath: '/studio/new'
      preLoaderRoute: typeof StudioNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstallRoute: InstallRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  StudioRoute: StudioRoute,
  AgentsSlugRoute: AgentsSlugRoute,
  ApiChatRoute: ApiChatRoute,
  LibrarySlugRoute: LibrarySlugRoute,
  StudioNewRoute: StudioNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
